apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: cloudnative

spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
      - name: backend

        image: docker.io/library/cloudnative-backend:latest

        imagePullPolicy: IfNotPresent

        ports:
        - containerPort: 5000

        env:
        - name: DB_HOST
          value: postgres

        - name: DB_PORT
          value: "5432"

        - name: DB_NAME
          value: notesdb

        - name: DB_USER
          value: notesuser

        - name: DB_PASSWORD
          value: Notes123
